In [3]:
import pandas as pd

In [4]:
df=pd.DataFrame({"price":[100,200,5000,3456,245]})
df

price
0    100
1    200
2   5000
3   3456
4    245

In [29]:
from sklearn.preprocessing import MinMaxScaler

In [47]:
Scaler=MinMaxScaler()
x_train_Scaled=Scaler.fit_transform(df[["price"]])

KeyError: "None of [Index(['price'], dtype='object')] are in the [columns]"

In [31]:
x_train_Scaled

array([[0.        ],
       [0.02040816],
       [1.        ],
       [0.68489796],
       [0.02959184]])

In [32]:
df=pd.read_table("CommViolPredUnnormalizedData.txt",sep=",",na_values="?")
df.head()

C:\Users\user10\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.


communityname state  countyCode  communityCode  fold  population  \
0  BerkeleyHeightstownship    NJ        39.0         5320.0     1       11980   
1           Marpletownship    PA        45.0        47616.0     1       23123   
2               Tigardcity    OR         NaN            NaN     1       29344   
3         Gloversvillecity    NY        35.0        29443.0     1       16656   
4              Bemidjicity    MN         7.0         5068.0     1       11245   

   householdsize  racepctblack  racePctWhite  racePctAsian  ...  burglaries  \
0           3.10          1.37         91.78          6.50  ...        14.0   
1           2.82          0.80         95.57          3.44  ...        57.0   
2           2.43          0.74         94.33          3.43  ...       274.0   
3           2.40          1.70         97.35          0.50  ...       225.0   
4           2.76          0.53         89.16          1.17  ...        91.0   

   burglPerPop  larcenies  larcPerPop  autoTheft  autoTheftPerPop  arsons  \
0       114.85      138.0     1132.08       16.0           131.26     2.0   
1       242.37      376.0     1598.78       26.0           110.55     1.0   
2       758.14     1797.0     4972.19      136.0           376.30    22.0   
3      1301.78      716.0     4142.56       47.0           271.93     NaN   
4       728.93     1060.0     8490.87       91.0           728.93     5.0   

   arsonsPerPop  ViolentCrimesPerPop  nonViolPerPop  
0         16.41                41.02        1394.59  
1          4.25               127.56        1955.95  
2         60.87               218.59        6167.51  
3           NaN               306.64            NaN  
4         40.05                  NaN        9988.79  

[5 rows x 147 columns]

In [33]:
df.shape

(2215, 147)

In [34]:
required_columns=[5,6]+list(range(11,26))+list(range(32,103))+[145]

In [37]:
df = df.iloc[:,required_columns]
df

population  householdsize  agePct12t21  agePct12t29  agePct16t24  \
0          11980           3.10        12.47        21.44        10.93   
1          23123           2.82        11.01        21.30        10.48   
2          29344           2.43        11.36        25.88        11.01   
3          16656           2.40        12.55        25.20        12.19   
4          11245           2.76        24.46        40.53        28.69   
5         140494           2.45        18.09        32.89        20.04   
6          28700           2.60        11.17        27.41        12.76   
7          59459           2.45        15.31        27.93        14.78   
8          74111           2.46        16.64        35.16        20.33   
9         103590           2.62        19.88        34.55        21.62   
10         31601           2.54        15.73        28.57        15.16   
11         25158           2.89        13.65        28.82        13.23   
12         40641           2.54        21.51        36.83        23.96   
13         57140           2.74        16.51        28.17        14.68   
14         13132           2.53        14.00        25.03        12.83   
15         30954           2.69        12.07        25.43        11.42   
16         45532           2.85        11.86        27.51        12.36   
17        180038           2.62        12.04        26.68        12.37   
18         14869           2.67        13.71        20.33         9.48   
19        261721           2.60        14.18        32.78        15.14   
20         50889           2.77        13.13        26.94        12.19   
21       7322564           2.60        13.06        27.46        13.09   
22         26436           3.34        16.16        37.22        19.09   
23         12183           2.36        11.29        26.87        12.20   
24         16023           2.63        11.91        23.09        10.33   
25         24692           2.54        12.84        25.81        11.93   
26         13842           2.35         8.23        18.30         6.98   
27         88693           2.70        13.77        30.92        15.15   
28         11235           2.60        14.59        25.62        12.02   
29         28259           2.86        16.26        28.79        13.83   
...          ...            ...          ...          ...          ...   
2185       48949           2.55        16.01        28.66        15.45   
2186       23252           2.19         9.99        20.61        10.00   
2187       15066           2.40         9.98        27.58        11.45   
2188       13198           2.55        10.18        22.31         9.41   
2189       16829           3.17        13.76        24.66        10.40   
2190       15372           3.04        13.09        21.16        10.79   
2191       13333           2.69        11.55        23.33        10.16   
2192       37825           2.91        13.73        23.88        12.80   
2193       29885           3.53        20.10        34.33        18.31   
2194       37520           2.92        14.67        27.32        12.40   
2195       20319           3.02        14.78        32.22        15.93   
2196       77759           2.64        23.36        38.80        26.50   
2197       14904           2.50         9.83        30.35        10.27   
2198       12208           2.77        13.29        25.34        13.25   
2199       25430           3.03        13.47        25.27        11.47   
2200       92703           2.49        13.45        27.70        13.93   
2201       24544           2.71        14.33        26.72        12.34   
2202       14203           2.97        15.13        27.38        12.31   
2203       27331           2.96        13.99        33.75        15.53   
2204       23875           2.67        13.62        25.83        11.67   
2205       14804           2.60        14.37        25.24        12.75   
2206       21732           2.42        12.90        22.30        10.07   
2207      

In [38]:
df.shape

(2215, 89)

In [39]:
df.isna().sum()

population                 0
householdsize              0
agePct12t21                0
agePct12t29                0
agePct16t24                0
agePct65up                 0
numbUrban                  0
pctUrban                   0
medIncome                  0
pctWWage                   0
pctWFarmSelf               0
pctWInvInc                 0
pctWSocSec                 0
pctWPubAsst                0
pctWRetire                 0
medFamInc                  0
perCapInc                  0
NumUnderPov                0
PctPopUnderPov             0
PctLess9thGrade            0
PctNotHSGrad               0
PctBSorMore                0
PctUnemployed              0
PctEmploy                  0
PctEmplManu                0
PctEmplProfServ            0
PctOccupManu               0
PctOccupMgmtProf           0
MalePctDivorce             0
MalePctNevMarr             0
                        ... 
PctHousLess3BR             0
MedNumBR                   0
HousVacant                 0
PctHousOccup  

In [40]:
df.dropna(inplace=True)

In [41]:
df.shape

(1994, 89)

In [42]:
x=df[df.columns[:-1]]
x.shape

(1994, 88)

In [43]:
y=df[df.columns[-1]]
y.shape

(1994,)

In [44]:
from sklearn.model_selection import train_test_split

In [46]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [62]:
from sklearn.preprocessing import MinMaxScaler

In [49]:
Scaler=MinMaxScaler()

In [65]:
x_train_Scaled=Scaler.fit_transform(x_train)

In [74]:
x_test_Scaled=Scaler.transform(x_test)

In [52]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [53]:
lineModel=LinearRegression()

In [57]:
lineModel.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

lineModel.score(x,y)*100

In [59]:
x_train.shape

(1395, 88)

In [60]:
lineModel1=LinearRegression()

In [71]:
lineModel1.fit(x_train_Scaled,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [75]:
lineModel1.score(x_test_Scaled,y_test)*100

59.77990704191234

In [76]:
from sklearn.linear_model import Ridge

In [77]:
ridgeModel=Ridge(alpha=1)
ridgeModel.fit(x_train,y_train)

Ridge(alpha=1, copy_X=True, fit_intercept=True, max_iter=None, normalize=False,
      random_state=None, solver='auto', tol=0.001)

In [78]:
ridgeModel.score(x_test,y_test)

0.598701195152752

In [79]:
ridgeModel.coef_

array([-5.37849034e-04,  2.66019825e+01,  1.60720256e+01, -2.71747111e+01,
        5.41925192e-01, -1.54468055e+01,  1.33845211e-05,  1.19205286e+00,
       -1.15302553e-02, -6.66852223e+00,  2.51663364e+01, -4.69012210e+00,
        1.08796342e+01,  1.16546469e+01, -1.02132339e+01,  5.57643358e-03,
        4.30066905e-03,  3.31643042e-04, -8.50346785e-01, -3.02797051e+01,
        1.38061183e+01,  1.02686952e+00, -4.75407912e+00,  1.01570146e+01,
       -3.45999180e+00, -9.62609881e-01,  1.22800631e+00,  7.72721938e+00,
        1.75601975e+02,  7.54337877e+00,  1.21059596e+02, -2.90823077e+02,
       -5.82141986e+00, -5.26094903e-01, -2.26098591e+01,  3.28215019e+00,
        1.13577334e-01,  3.84671865e+00, -9.17919481e+00, -5.87925935e-03,
        5.12365747e+01, -4.49108552e-04,  2.65504755e+00, -1.93099651e-01,
       -7.54053116e-01,  3.72733906e-01, -5.08580286e+01,  6.05149388e-01,
       -6.56781562e+00,  8.00278919e+00,  6.78372099e-01, -1.16442966e+01,
        3.24080463e+00, -

In [80]:
ridgeModel.coef_**2

array([2.89281583e-07, 7.07665472e+02, 2.58310007e+02, 7.38464923e+02,
       2.93682913e-01, 2.38603800e+02, 1.79145406e-10, 1.42099002e+00,
       1.32946786e-04, 4.44691887e+01, 6.33344488e+02, 2.19972454e+01,
       1.18366440e+02, 1.35830795e+02, 1.04310147e+02, 3.10966115e-05,
       1.84957543e-05, 1.09987107e-07, 7.23089655e-01, 9.16860544e+02,
       1.90608902e+02, 1.05446101e+00, 2.26012682e+01, 1.03164945e+02,
       1.19715432e+01, 9.26617782e-01, 1.50799950e+00, 5.97099193e+01,
       3.08360535e+04, 5.69025633e+01, 1.46554258e+04, 8.45780623e+04,
       3.38889292e+01, 2.76775847e-01, 5.11205727e+02, 1.07725099e+01,
       1.28998109e-02, 1.47972444e+01, 8.42576174e+01, 3.45656905e-05,
       2.62518659e+03, 2.01698492e-07, 7.04927748e+00, 3.72874751e-02,
       5.68596101e-01, 1.38930565e-01, 2.58653907e+03, 3.66205781e-01,
       4.31362020e+01, 6.40446348e+01, 4.60188705e-01, 1.35589642e+02,
       1.05028147e+01, 7.30612695e+02, 6.66303515e+04, 5.12447086e+04,
      

In [81]:
sum(ridgeModel.coef_**2)

356251.02632268233

In [82]:
ridgeModel.fit(x_train,y_train)

Ridge(alpha=1, copy_X=True, fit_intercept=True, max_iter=None, normalize=False,
      random_state=None, solver='auto', tol=0.001)

In [83]:
ridgeModel.score(x,y)*100

65.72639133595437

In [86]:
ridgeModel1=Ridge(alpha=1)
ridgeModel1.fit(x_train_Scaled,y_train)

Ridge(alpha=1, copy_X=True, fit_intercept=True, max_iter=None, normalize=False,
      random_state=None, solver='auto', tol=0.001)

In [88]:
ridgeModel1.score(x_test_Scaled,y_test)

0.6063639158439716